services:
  postgres:
    image: ${POSTGRES_IMAGE-postgres:15.2-alpine}
    container_name: ztnet-local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - ztnet-local

#  zerotier:
#    image: ${ZEROTIER_IMAGE-zyclonite/zerotier:1.14.2}
#    hostname: zerotier
#    container_name: ztnet-local-zerotier
#    restart: unless-stopped
#    volumes:
#      - ./.data/zerotier:/var/lib/zerotier-one
#    cap_add:
#      - NET_ADMIN
#      - SYS_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    networks:
#      - ztnet-local
#    environment:
#      - ZT_OVERRIDE_LOCAL_CONF=true
#      - ZT_ALLOW_MANAGEMENT_FROM=172.31.254.0/29

  ztnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODEJS_IMAGE: ${NODEJS_IMAGE-node:24-bookworm-slim}
        APT_MIRROR: ${APT_MIRROR-http://mirrors.aliyun.com/debian}
        APT_SECURITY_MIRROR: ${APT_SECURITY_MIRROR-http://mirrors.aliyun.com/debian-security}
        NPM_REGISTRY: ${NPM_REGISTRY-https://registry.npmmirror.com}
        PRISMA_ENGINES_MIRROR: ${PRISMA_ENGINES_MIRROR-https://cdn.npmmirror.com/binaries/prisma}
    image: ztnet:local
    container_name: ztnet-local-app
    working_dir: /app
    restart: unless-stopped
    ports:
      - "9000:3000"
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ztnet
      NEXTAUTH_URL: https://planet.dadastory.com
      NEXTAUTH_SECRET: 7e56c614e645f67e4cbef38f2a7cf2ac280f03ca12f6141e8d01f90a69736218
      NEXTAUTH_URL_INTERNAL: http://ztnet:3000
      ZT_ADDR: http://host.docker.internal:9993
      ZT_SECRET: djlzb4wad3l0hu0afr1lp6lm
    networks:
      - ztnet-local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
#      - zerotier

networks:
  ztnet-local:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.31.254.0/29
